# Generated by Django 5.2.1 on 2025-05-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='phonepe_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
